### ISSUE TITLE
The `domain` property collides with the same property on `EventEmitter`, causing a crash

### ISSUE THREAD

**Issue by AlCalzone** [joostth/sucks.js#2]
https://github.com/joostth/sucks.js/blob/8d6062b2ecdf8dd4687cf9c30dde1dede00dcc04/index.js#L464

This leads to ugly crashes when using this module, see https://forum.iobroker.net/viewtopic.php?p=172861#p172861
Also see this discussion for reference: https://github.com/nodejs/node-v0.x-archive/issues/3922

Basically a class inheriting from `EventEmitter` must not have a `domain` property.

**Comment by AlCalzone** [comment]
Proposed fix is at #3

**Comment by joostth** [comment]
Thanks for posting the issue and providing the related fix in the pull request. Fix is included in v0.0.4 now available on [npm](https://www.npmjs.com/package/sucks).

**Comment by AlCalzone** [comment]
Thanks for the quick reaction :)
